spring.application.name=consumer
# ===============================
# CONFIGURACIÓN DE KAFKA CONSUMER
# ===============================
# Dirección del broker para desarrollo local (IntelliJ).
# Docker la sobrescribe con la variable de entorno.
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Producer Properties (for DLT)
# This is crucial: it tells the DeadLetterPublishingRecoverer how to serialize the
# failed message object back to JSON before sending it to the DLT.
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ===============================
# CONFIGURACIN DE ACTUATOR
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
server.port=8081 # Puerto diferente al producer para evitar conflictos si se ejecuta localmente 