spring.application.name=producer
# ===============================
# PUERTO DE LA APLICACIÓN
# ===============================
server.port=8080

# ===============================
# CONFIGURACIÓN DE KAFKA PRODUCER
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Usamos JsonSerializer para enviar objetos PersonaDTO como JSON
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# ===============================
# CONFIGURACIÓN DE LA BASE DE DATOS (R2DBC con H2 en memoria)
# ===============================
spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=
spring.sql.init.mode=always

# ===============================
# CONFIGURACIÓN DE ACTUATOR (PARA MÉTRICAS Y HEALTH CHECKS)
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración para que el nombre de la tabla sea 'personas' y no se genere uno aleatorio
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permitir la sobreescritura de beans para resolver el conflicto entre
# la configuración de seguridad de Web y WebFlux.
spring.main.allow-bean-definition-overriding=true   